site_name: GLEngine Documentation
repo_url: https://github.com/popwser/GLEngine/
repo_name: GitHub
edit_uri: ""
site_author: michaelbuerger

theme:
  name: "material"

markdown_extensions:
  - codehilite
  - admonition

extra:
  manifest: "manifest.webmanifest"

nav:
  - Home: index.md
  - Getting Started: gettingstarted/index.md
  - Reference: reference/index.md
  - Contributing: contributing/index.md
  - License: license.md
